-- Hashing, in plain SQL so that every platform computes identical results.
--
-- Callers insert (algo, input) rows into hash_input; the trigger below computes each hash once,
-- stores it in hash_memo and empties the queue. Readers then join hash_memo.
--   algo 'djb2'   : DJB2 over UTF-16 code units, as an unsigned 32-bit decimal string. Used for
--                   entity names when the server hashed them with djb2, and for user hashes.
--   algo 'sha256' : base64(SHA-256(UTF-8 bytes)). Entity names for sha256/legacy payloads.
--   algo 'bucket' : first 64 bits of SHA-256 as an unsigned integer, modulo 10000. On-device
--                   evaluation buckets (pass percentages use % 10000, user_bucket uses % 1000).

-- name: schema

CREATE TEMP TABLE IF NOT EXISTS hash_input (
  algo TEXT NOT NULL,
  input TEXT NOT NULL
);

-- djb2 requests can also go here: a statement inserting into hash_input is compiled with the
-- (large) SHA-256 program, one inserting into djb2_input is not.
CREATE TEMP TABLE IF NOT EXISTS djb2_input (
  input TEXT NOT NULL
);

CREATE TEMP TABLE IF NOT EXISTS hash_memo (
  algo TEXT NOT NULL,
  input TEXT NOT NULL,
  output TEXT NOT NULL,
  PRIMARY KEY (algo, input)
);

-- 31^k mod 2^32 for k < 512. DJB2 is h = 31 * h + c per UTF-16 unit, so for n units
-- h = sum(c_i * 31^(n - i)) mod 2^32: one indexed scan instead of a recursion. (TEMP: a main
-- table would make every statement reading it take the database file lock.)
CREATE TEMP TABLE IF NOT EXISTS djb2_pow (
  k INTEGER PRIMARY KEY,
  p INTEGER NOT NULL
);
INSERT OR IGNORE INTO djb2_pow (k, p)
  WITH RECURSIVE w(k, p) AS (SELECT 0, 1 UNION ALL SELECT k + 1, (p * 31) & 4294967295 FROM w WHERE k < 511)
  SELECT k, p FROM w WHERE NOT EXISTS (SELECT 1 FROM djb2_pow WHERE k = 511);

CREATE TEMP VIEW IF NOT EXISTS djb2_output AS
WITH RECURSIVE
  -- The sum form, for inputs of up to 512 characters, none of them outside the BMP (NULL
  -- otherwise: count(*) falls short of the length, or a character needs two UTF-16 units).
  -- The same expression is inlined in get_value.
  fast(input, h) AS (
    SELECT i.input, (
      SELECT CASE WHEN count(*) = length(i.input) AND max(c) <= 65535 THEN sum(c * p) & 4294967295 END
      FROM (SELECT unicode(substr(i.input, length(i.input) - k, 1)) AS c, p
            FROM djb2_pow WHERE k < length(i.input)))
    FROM (SELECT input FROM hash_input WHERE algo = 'djb2' UNION ALL SELECT input FROM djb2_input) AS i
  ),
  -- Otherwise one row per character; astral characters count as a UTF-16 surrogate pair (two steps)
  d(input, i, n, h) AS (
    SELECT input, 1, length(input), 0 FROM fast WHERE h IS NULL
    UNION ALL
    SELECT input, i + 1, n,
      CASE WHEN unicode(substr(input, i, 1)) > 65535 THEN
        (((((h << 5) - h + 55296 + ((unicode(substr(input, i, 1)) - 65536) >> 10)) & 4294967295) << 5)
          - (((h << 5) - h + 55296 + ((unicode(substr(input, i, 1)) - 65536) >> 10)) & 4294967295)
          + 56320 + ((unicode(substr(input, i, 1)) - 65536) & 1023)) & 4294967295
      ELSE ((h << 5) - h + unicode(substr(input, i, 1))) & 4294967295
      END
    FROM d WHERE i <= n
  )
SELECT 'djb2' AS algo, input, CAST(h AS TEXT) AS output FROM fast WHERE h IS NOT NULL
UNION ALL
SELECT 'djb2' AS algo, input, CAST(h AS TEXT) AS output FROM d WHERE i = n + 1;



CREATE TEMP TRIGGER IF NOT EXISTS hash_input_djb2 AFTER INSERT ON hash_input
WHEN NEW.algo = 'djb2'
BEGIN
  INSERT OR IGNORE INTO hash_memo (algo, input, output) SELECT algo, input, output FROM djb2_output;
  DELETE FROM hash_input;
END;

CREATE TEMP TRIGGER IF NOT EXISTS djb2_input_memo AFTER INSERT ON djb2_input
BEGIN
  INSERT OR IGNORE INTO hash_memo (algo, input, output) SELECT algo, input, output FROM djb2_output;
  DELETE FROM djb2_input;
END;



-- name: trim_hash_memo
-- Keeps the memo bounded (like the original BoundedMemo): only the newest 2048 hashes stay.
-- Run between blocks, never while a block still relies on the hashes it just computed.
DELETE FROM hash_memo WHERE rowid <= (SELECT max(rowid) FROM hash_memo) - 2048;


-- name: sha256_schema
-- SHA-256 hashing (sha256 / bucket rows of hash_input). A large program, so it is created only on
-- connections that need it: blocks that hash with it declare `@needs: sha256_schema`.
-- SHA-256 as a recursive CTE: one row per compression round (t = 0..63) plus one row per block
-- (t = 64) that folds the round state into h0..h7. Bitwise XOR is written arithmetically:
-- x ^ y ^ z = x + y + z - 2(x&y + x&z + y&z) + 4(x&y&z). Generated by tools/gen_sha256_sql.py.
CREATE TEMP VIEW IF NOT EXISTS sha256_output AS
WITH RECURSIVE
  sha256_msg(algo, input, hex, nblocks) AS (
    SELECT algo, input,
      hex(CAST(input AS BLOB)) || '80'
        || hex(zeroblob(((55 - length(CAST(input AS BLOB))) % 64 + 64) % 64))
        || printf('%016X', length(CAST(input AS BLOB)) * 8),
      (length(CAST(input AS BLOB)) + 8) / 64 + 1
    FROM hash_input WHERE algo IN ('sha256', 'bucket')
  ),
  sha256_k(t, k) AS (VALUES (0,1116352408),(1,1899447441),(2,3049323471),(3,3921009573),(4,961987163),(5,1508970993),(6,2453635748),(7,2870763221),(8,3624381080),(9,310598401),(10,607225278),(11,1426881987),(12,1925078388),(13,2162078206),(14,2614888103),(15,3248222580),(16,3835390401),(17,4022224774),(18,264347078),(19,604807628),(20,770255983),(21,1249150122),(22,1555081692),(23,1996064986),(24,2554220882),(25,2821834349),(26,2952996808),(27,3210313671),(28,3336571891),(29,3584528711),(30,113926993),(31,338241895),(32,666307205),(33,773529912),(34,1294757372),(35,1396182291),(36,1695183700),(37,1986661051),(38,2177026350),(39,2456956037),(40,2730485921),(41,2820302411),(42,3259730800),(43,3345764771),(44,3516065817),(45,3600352804),(46,4094571909),(47,275423344),(48,430227734),(49,506948616),(50,659060556),(51,883997877),(52,958139571),(53,1322822218),(54,1537002063),(55,1747873779),(56,1955562222),(57,2024104815),(58,2227730452),(59,2361852424),(60,2428436474),(61,2756734187),(62,3204031479),(63,3329325298)),
  sha256_state(algo, input, blk, t, nblocks, h0, h1, h2, h3, h4, h5, h6, h7, a, b, c, d, e, f, g, h, w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15) AS (
    SELECT m.algo, m.input, 0, 0, m.nblocks, 1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225, 1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 1, 1)) - 1) << 28) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 2, 1)) - 1) << 24) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 3, 1)) - 1) << 20) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 4, 1)) - 1) << 16) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 5, 1)) - 1) << 12) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 6, 1)) - 1) << 8) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 7, 1)) - 1) << 4) | ((instr('0123456789ABCDEF', substr(m.hex, ((0) * 128 + (0) * 8) + 8, 1)) - 1) << 0)) FROM sha256_msg m
    UNION ALL
    SELECT
      s.algo,
      s.input,
      CASE WHEN s.t < 64 THEN s.blk ELSE s.blk + 1 END,
      CASE WHEN s.t < 64 THEN s.t + 1 ELSE 0 END,
      s.nblocks,
      CASE WHEN s.t < 64 THEN s.h0 ELSE (s.h0 + s.a) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h1 ELSE (s.h1 + s.b) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h2 ELSE (s.h2 + s.c) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h3 ELSE (s.h3 + s.d) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h4 ELSE (s.h4 + s.e) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h5 ELSE (s.h5 + s.f) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h6 ELSE (s.h6 + s.g) & 4294967295 END,
      CASE WHEN s.t < 64 THEN s.h7 ELSE (s.h7 + s.h) & 4294967295 END,
      CASE WHEN s.t < 64 THEN ((h + ((((e >> 6) | (e << 26)) & 4294967295) + (((e >> 11) | (e << 21)) & 4294967295) + (((e >> 25) | (e << 7)) & 4294967295) - 2 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 11) | (e << 21)) & 4294967295))) - 2 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295))) - 2 * (((((e >> 11) | (e << 21)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295))) + 4 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 11) | (e << 21)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295)))) + ((e & f) | ((~e & 4294967295) & g)) + k.k + w15) + (((((a >> 2) | (a << 30)) & 4294967295) + (((a >> 13) | (a << 19)) & 4294967295) + (((a >> 22) | (a << 10)) & 4294967295) - 2 * (((((a >> 2) | (a << 30)) & 4294967295)) & ((((a >> 13) | (a << 19)) & 4294967295))) - 2 * (((((a >> 2) | (a << 30)) & 4294967295)) & ((((a >> 22) | (a << 10)) & 4294967295))) - 2 * (((((a >> 13) | (a << 19)) & 4294967295)) & ((((a >> 22) | (a << 10)) & 4294967295))) + 4 * (((((a >> 2) | (a << 30)) & 4294967295)) & ((((a >> 13) | (a << 19)) & 4294967295)) & ((((a >> 22) | (a << 10)) & 4294967295)))) + ((a & b) | (a & c) | (b & c)))) & 4294967295 ELSE (s.h0 + s.a) & 4294967295 END,
      CASE WHEN s.t < 64 THEN a ELSE (s.h1 + s.b) & 4294967295 END,
      CASE WHEN s.t < 64 THEN b ELSE (s.h2 + s.c) & 4294967295 END,
      CASE WHEN s.t < 64 THEN c ELSE (s.h3 + s.d) & 4294967295 END,
      CASE WHEN s.t < 64 THEN (d + (h + ((((e >> 6) | (e << 26)) & 4294967295) + (((e >> 11) | (e << 21)) & 4294967295) + (((e >> 25) | (e << 7)) & 4294967295) - 2 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 11) | (e << 21)) & 4294967295))) - 2 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295))) - 2 * (((((e >> 11) | (e << 21)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295))) + 4 * (((((e >> 6) | (e << 26)) & 4294967295)) & ((((e >> 11) | (e << 21)) & 4294967295)) & ((((e >> 25) | (e << 7)) & 4294967295)))) + ((e & f) | ((~e & 4294967295) & g)) + k.k + w15)) & 4294967295 ELSE (s.h4 + s.e) & 4294967295 END,
      CASE WHEN s.t < 64 THEN e ELSE (s.h5 + s.f) & 4294967295 END,
      CASE WHEN s.t < 64 THEN f ELSE (s.h6 + s.g) & 4294967295 END,
      CASE WHEN s.t < 64 THEN g ELSE (s.h7 + s.h) & 4294967295 END,
      CASE WHEN s.t < 64 THEN w1 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w2 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w3 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w4 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w5 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w6 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w7 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w8 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w9 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w10 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w11 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w12 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w13 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w14 ELSE 0 END,
      CASE WHEN s.t < 64 THEN w15 ELSE 0 END,
      CASE WHEN s.t < 64 THEN CASE WHEN s.t < 15 THEN (((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 1, 1)) - 1) << 28) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 2, 1)) - 1) << 24) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 3, 1)) - 1) << 20) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 4, 1)) - 1) << 16) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 5, 1)) - 1) << 12) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 6, 1)) - 1) << 8) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 7, 1)) - 1) << 4) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk) * 128 + (s.t + 1) * 8) + 8, 1)) - 1) << 0)) ELSE ((((((w14 >> 17) | (w14 << 15)) & 4294967295) + (((w14 >> 19) | (w14 << 13)) & 4294967295) + (w14 >> 10) - 2 * (((((w14 >> 17) | (w14 << 15)) & 4294967295)) & ((((w14 >> 19) | (w14 << 13)) & 4294967295))) - 2 * (((((w14 >> 17) | (w14 << 15)) & 4294967295)) & ((w14 >> 10))) - 2 * (((((w14 >> 19) | (w14 << 13)) & 4294967295)) & ((w14 >> 10))) + 4 * (((((w14 >> 17) | (w14 << 15)) & 4294967295)) & ((((w14 >> 19) | (w14 << 13)) & 4294967295)) & ((w14 >> 10)))) + w9 + ((((w1 >> 7) | (w1 << 25)) & 4294967295) + (((w1 >> 18) | (w1 << 14)) & 4294967295) + (w1 >> 3) - 2 * (((((w1 >> 7) | (w1 << 25)) & 4294967295)) & ((((w1 >> 18) | (w1 << 14)) & 4294967295))) - 2 * (((((w1 >> 7) | (w1 << 25)) & 4294967295)) & ((w1 >> 3))) - 2 * (((((w1 >> 18) | (w1 << 14)) & 4294967295)) & ((w1 >> 3))) + 4 * (((((w1 >> 7) | (w1 << 25)) & 4294967295)) & ((((w1 >> 18) | (w1 << 14)) & 4294967295)) & ((w1 >> 3)))) + w0) & 4294967295) END ELSE CASE WHEN s.blk + 1 < s.nblocks THEN (((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 1, 1)) - 1) << 28) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 2, 1)) - 1) << 24) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 3, 1)) - 1) << 20) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 4, 1)) - 1) << 16) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 5, 1)) - 1) << 12) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 6, 1)) - 1) << 8) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 7, 1)) - 1) << 4) | ((instr('0123456789ABCDEF', substr(m.hex, ((s.blk + 1) * 128 + (0) * 8) + 8, 1)) - 1) << 0)) ELSE 0 END END
    FROM sha256_state s
      JOIN sha256_msg m ON m.input = s.input AND m.algo = s.algo
      LEFT JOIN sha256_k k ON k.t = s.t
    WHERE s.blk < s.nblocks
  )
  ,
  digest(algo, input, h0, h1, hex) AS (
    SELECT algo, input, h0, h1,
      printf('%08X%08X%08X%08X%08X%08X%08X%08X', h0, h1, h2, h3, h4, h5, h6, h7)
    FROM sha256_state WHERE blk = nblocks
  ),
  -- base64 over the 32 digest bytes: ten 3-byte groups, then 2 bytes + '='
  b64(algo, input, pos, out, hex) AS (
    SELECT algo, input, 0, '', hex FROM digest WHERE algo = 'sha256'
    UNION ALL
    SELECT algo, input, pos + 6,
      out || (
        WITH g(n) AS (SELECT
          ((instr('0123456789ABCDEF', substr(hex, pos + 1, 1)) - 1) << 20)
          | ((instr('0123456789ABCDEF', substr(hex, pos + 2, 1)) - 1) << 16)
          | ((instr('0123456789ABCDEF', substr(hex, pos + 3, 1)) - 1) << 12)
          | ((instr('0123456789ABCDEF', substr(hex, pos + 4, 1)) - 1) << 8)
          | (CASE WHEN pos + 6 <= 64 THEN
              ((instr('0123456789ABCDEF', substr(hex, pos + 5, 1)) - 1) << 4)
              | (instr('0123456789ABCDEF', substr(hex, pos + 6, 1)) - 1)
             ELSE 0 END))
        SELECT substr('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', ((n >> 18) & 63) + 1, 1)
          || substr('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', ((n >> 12) & 63) + 1, 1)
          || substr('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', ((n >> 6) & 63) + 1, 1)
          || CASE WHEN pos + 6 <= 64
               THEN substr('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', (n & 63) + 1, 1)
               ELSE '=' END
        FROM g),
      hex
    FROM b64 WHERE pos < 64
  )
SELECT algo, input, out AS output FROM b64 WHERE pos >= 64
UNION ALL
-- (h0 * 2^32 + h1) mod 10000, without overflowing a signed 64-bit integer; 2^32 mod 10000 = 7296
SELECT algo, input, CAST(((h0 % 10000) * 7296 + h1 % 10000) % 10000 AS TEXT) FROM digest WHERE algo = 'bucket';

CREATE TEMP TRIGGER IF NOT EXISTS hash_input_sha256 AFTER INSERT ON hash_input
WHEN NEW.algo <> 'djb2'
BEGIN
  INSERT OR IGNORE INTO hash_memo (algo, input, output) SELECT algo, input, output FROM sha256_output;
  DELETE FROM hash_input;
END;
